name: Deploy to 1Panel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 81.68.195.216 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh ubuntu@81.68.195.216 'cd /opt/1panel/apps/openresty/openresty/www/sites/learn-web-2024.xuchunyang.cn/index && git pull && sudo docker run --rm -v "$PWD":/usr/src/app -w /usr/src/app -u 1000:1000 node bash -c "npm ci && npm run build"'
